"""empty message

Revision ID: 37b0e85fd38a
Revises: 58705c94ecba
Create Date: 2023-12-14 23:00:47.150583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b0e85fd38a'
down_revision = '58705c94ecba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifynumber', sa.String(length=50), nullable=True))

    with op.batch_alter_table('similar_products', schema=None) as batch_op:
        batch_op.drop_column('identifynumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifynumber', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('identifynumber')

    # ### end Alembic commands ###
